package_update: true 

packages:
  - python3
  - python3-pip
  - python3-virtualenv
runcmd:
  - DEBIAN_FRONTEND=noninteractive export VERSION=3.11.2 
  - DEBIAN_FRONTEND=noninteractive mkdir -p /sylabs
  - DEBIAN_FRONTEND=noninteractive cd /sylabs && wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce_${VERSION}-jammy_amd64.deb 
  - DEBIAN_FRONTEND=noninteractive cd /sylabs && sudo apt-get install /sylabs/singularity-ce_${VERSION}-jammy_amd64.deb -y
